"""Hopefully fix the models with connection to DB w/ new instance

Revision ID: 6e1be4188225
Revises: 22c5ae9b32cd
Create Date: 2023-03-29 15:30:56.542846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e1be4188225'
down_revision = '22c5ae9b32cd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'add_drinks', type_='foreignkey')
    op.create_foreign_key(None, 'add_drinks', 'orders', ['order_number'], ['id'])
    op.create_foreign_key(None, 'add_drinks', 'drinks', ['drink_name'], ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'add_drinks', type_='foreignkey')
    op.drop_constraint(None, 'add_drinks', type_='foreignkey')
    op.create_foreign_key(None, 'add_drinks', 'drinks', ['drink_name'], ['id'])
    # ### end Alembic commands ###
